build-and-run-tests:
  stage: test
  script:
    - python3 -m venv venv
    - . ./venv/bin/activate
    - ./venv/bin/python -m pip install -r requirements.txt
    - . .env
    - docker run --name mongo -d -p 0.0.0.0:27017:27017 mongo
    - sleep 3
    - cd quizer
    - python -m coverage run runtests.py
    - coverage report
    - docker-compose build