#!/bin/sh
cp "./requirements.txt" "./docker/requirements.txt"
cp -r "./quizer" "./docker/quizer"
cp ./docker/config.py ./docker/quizer/quizer/config.py
cp ./docker/config.py ./docker/quizer/main/config.py
rm -r "./docker/quizer/__pycache__" 2> /dev/null
echo "========================================Start building Quizer Docker image========================================"
sudo docker build -t quizer docker
rm "./docker/requirements.txt"
rm -r "./docker/quizer"
echo "====================Docker image has been built successfully. Enter 'docker run quizer' to run it================="
