#!/bin/bash

echo "========================================Updating data for Docker image============================================"
rm "./docker/requirments.txt" 2> /dev/null
rm -r "./docker/quizer" 2> /dev/null
cp "./requirements.txt" "./docker/requirements.txt"
cp -r "$./quizer" "./docker/quizer"
rm -r "./docker/quizer/__pycache__" 2> /dev/null
echo "====================================Start building Quizer Docker image========================================"
sudo docker build -t quizer docker
echo "=======================Project has been built successfully. Enter 'docker run quizer' to run it==================="