#!/bin/bash
source ./venv/bin/activate 2>/dev/null
if [ "$?" -eq "1" ]
then
  echo "Error on activating venv. Have you created it? (python3 -m venv venv)"
  exit 1
fi
mkdir tmp
cp -r quizer tmp/quizer
rm -r quizer
echo "===========================================Start loading requirements==========================================="
pip install --no-cache-dir -r requirements.txt
echo "=========================================Successfully loaded requeirments======================================="
django-admin startproject quizer
cd quizer
python manage.py startapp main
cd ..
rm -r quizer
cp -r tmp/quizer quizer
rm -r tmp
python quizer/manage.py makemigrations
python quizer/manage.py migrate
echo "===========================================Initialized django app==============================================="
echo "==========================================Enter configuration data============================================="
read -r -p "MongoDB host: " MONGO_HOST
if [ "${MONGO_HOST}" == "" ]
then
  MONGO_HOST="localhost"
  echo "MONGO_HOST = '${MONGO_HOST}'" >> config.py
fi

read -r -p "MongoDB port: " MONGO_PORT
if [ "${MONGO_PORT}" == "" ]
then
  MONGO_PORT="27017"
  echo "MONGO_PORT = '${MONGO_PORT}'" >> config.py
fi

read -r -p "MongoDB user: " MONGO_USER
if [ "${MONGO_USER}" == "" ]
then
  MONGO_USER=""
  echo "MONGO_USER = '${MONGO_USER}'" >> config.py
fi

read -r -p "MongoDB password: " MONGO_PASSWORD
if [ "${MONGO_PASSWORD}" == "" ]
then
  MONGO_PASSWORD=""
  echo "MONGO_USER = '${MONGO_PASSWORD}'" >> config.py
fi

read -r -p "MongoDB database name: " MONGO_DBNAME
if [ "${MONGO_DBNAME}" == "" ]
then
  MONGO_DBNAME="quizer"
  echo "MONGO_USER = '${MONGO_DBNAME}'" >> config.py
fi

cp config.py ./quizer/quizer/config.py
mv config.py ./quizer/main/config.py

echo "===========================================Start creating groups==============================================="

echo 'from django.contrib.auth.models import Group; l = Group(id=1, name="lecturer"); l.save()' | python quizer/manage.py shell
echo "Created 'lecturer' group"
echo 'from django.contrib.auth.models import Group; s = Group(id=2, name="student"); s.save()' | python quizer/manage.py shell
echo "Created 'student' group"
echo "===========================================Enter superuser info==============================================="
python quizer/manage.py createsuperuser
echo 'from django.contrib.auth.models import User; a = User.objects.get(id=1); a.groups.add(1); a.save(); print("Added user %s to group %s" % (a.username, "lecturer"))'  | python quizer/manage.py shell
echo 'from django.contrib.auth.models import User; s = User(id=4, username="user"); s.set_password("password"); s.groups.add(2); s.save()' | python quizer/manage.py shell
echo "Added user 'user' with password 'password' to group 'student'"

read -r -p "Build docker image? [y/n]" BUILD_DOCKER

if [ "${BUILD_DOCKER}" == "y" ]
then
  echo "========================================Updating data for Docker image============================================"
  rm "./docker/requirments.txt" 2> /dev/null
  rm -r "./docker/quizer" 2> /dev/null
  cp "./requirements.txt" "./docker/requirements.txt"
  cp -r "./quizer" "./docker/quizer"
  rm -r "./docker/quizer/__pycache__" 2> /dev/null
  echo "========================================Start building Quizer Docker image========================================"
  sudo docker build -t quizer docker
  echo "====================Docker image has been built successfully. Enter 'docker run quizer' to run it================="
fi
