version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: quizer-mongo
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - backend

  web:
    build: .
    container_name: quizer
    restart: unless-stopped
    ports:
      - 8000:80
    depends_on:
      - mongo
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
    driver: bridge