version: '3'

services:
  db:
    image: postgres:latest
    container_name: quizer-postgres
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - backend

  web:
    build: .
    container_name: quizer-web
    restart: unless-stopped
    ports:
      - 8000:80
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    networks:
      - backend

networks:
  backend:
    driver: bridge