version: '3'

services:
  db:
    image: postgres:13.0
    container_name: quizer-postgres
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - quizer_db_data:/var/lib/postgresql/data/

  web:
    build: .
    image: web-testing-tool:1.0
    container_name: quizer-web
    restart: unless-stopped
    volumes:
      - quizer_static_data:/usr/share/python3/quizer/static
      - quizer_media_data:/usr/share/python3/quizer/media
    ports:
      - 8000:80
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  quizer_db_data:
  quizer_media_data:
  quizer_static_data: