#!/bin/bash

if [ $# -lt 1 ]
then
    echo "Error: required params: PROJECT_DIR"
    exit 1
fi

if [ "$1" == "default" ]
then
    PROJECT_DIR="/home/leadness/Stude/Quizer"
    echo "Project directory: ${PROJECT_DIR}"
else
    if [ -d "$1" ]
    then
        PROJECT_DIR="$1"
        if [ "$1" == "." ]
        then
            echo "Project directory: $(pwd)"
        else
            echo "Project directory: ${PROJECT_DIR}"
        fi
    else
        echo "Error: ${1} is not dir"
        exit 1
    fi
fi

rm "./docker/requirments.txt" 2> /dev/null
rm -r "./docker/quizer" 2> /dev/null
cp "${PROJECT_DIR}/requirements.txt" "./docker/requirements.txt"
cp -r "${PROJECT_DIR}/quizer" "./docker/quizer"
rm -r "./docker/quizer/__pycache__"

rm "./docker/quizer/config/config.json"
rm "./docker/quizer/config/default_config.json"

CONFIG="{\"mdb_host\": \"mongo\", \"mdb_port\": 27017}"
echo "${CONFIG}" >> "./docker/quizer/config/config.json"
echo "${CONFIG}" >> "./docker/quizer/config/default_config.json"

CONFIG=$(cat ./docker/quizer/config.py)
rm "./docker/quizer/config.py"
echo "${CONFIG//\'config/\'/app/quizer/config}" >> "./docker/quizer/config.py"
