#!/bin/bash

if [ $# -lt 1 ]
then
    echo "Error: required params: PROJECT_DIR"
    exit 1
fi

if [ -d "${1}" ]
    then
        PROJECT_DIR="${1}"
        if [ "${1}" == "." ]
        then
            echo "Project directory: $(pwd)"
        else
            echo "Project directory: ${PROJECT_DIR}"
        fi
    else
        echo "Error: ${1} is not dir"
        exit 1
    fi

rm "./docker/requirments.txt" 2> /dev/null
rm -r "./docker/quizer" 2> /dev/null
cp "${PROJECT_DIR}/requirements.txt" "./docker/requirements.txt"
cp -r "${PROJECT_DIR}/quizer" "./docker/quizer"
rm -r "./docker/quizer/__pycache__"