# Generated by Django 3.1.13 on 2021-10-24 15:12

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Название дисциплины"),
                ),
                (
                    "description",
                    models.TextField(default="", verbose_name="Описание дисциплины"),
                ),
            ],
            options={
                "verbose_name": "Дисциплина",
                "verbose_name_plural": "Дисциплины",
            },
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Тема теста")),
                (
                    "description",
                    models.TextField(default="", verbose_name="Описание теста"),
                ),
                (
                    "tasks_num",
                    models.IntegerField(
                        default=0, verbose_name="Количество заданий в тесте"
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        default=300, verbose_name="Длительность теста в секундах"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Составитель",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="main.subject",
                        verbose_name="Предмет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тест",
                "verbose_name_plural": "Тесты",
            },
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_running", models.BooleanField(verbose_name="Тест еще запущен")),
                (
                    "comment",
                    models.TextField(
                        default="", verbose_name="Комментарий преподавателя"
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Время запуска тестирования",
                    ),
                ),
                (
                    "launched_lecturer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="testing_results",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь, запустивный тест",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="testing_results",
                        to="main.subject",
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="testing_results",
                        to="main.test",
                        verbose_name="Тест",
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат тестирования",
                "verbose_name_plural": "Результаты тестирований",
                "db_table": "main_tests_results",
            },
        ),
        migrations.CreateModel(
            name="UserResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    models.IntegerField(verbose_name="Продолжительность тестирования"),
                ),
                (
                    "tasks_num",
                    models.IntegerField(verbose_name="Число заданий в тесте"),
                ),
                (
                    "right_answers_count",
                    models.IntegerField(verbose_name="Число правильных ответов"),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Время прохождения тестирования",
                    ),
                ),
                ("questions", django.contrib.postgres.fields.jsonb.JSONField()),
                (
                    "testing_result",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="results",
                        to="main.testresult",
                        verbose_name="Результаты тестирования",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="results",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Прошедший тестирование",
                    ),
                ),
            ],
            options={
                "verbose_name": "Персональный результат тестирования",
                "verbose_name_plural": "Персональные результаты тестирований",
                "db_table": "main_user_results",
            },
        ),
        migrations.CreateModel(
            name="RunningTestsAnswers",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_duration",
                    models.IntegerField(verbose_name="Длительность теста"),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Время запуска теста",
                    ),
                ),
                ("right_answers", django.contrib.postgres.fields.jsonb.JSONField()),
                (
                    "test",
                    models.ForeignKey(
                        default=0,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="right_answers",
                        to="main.test",
                        verbose_name="Запущенный тест",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=0,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="right_answers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь, проходящий тест",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответы за запущенные тесты",
                "verbose_name_plural": "Ответы за запущенные тесты",
                "db_table": "main_running_tests_answers",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "formulation",
                    models.CharField(
                        max_length=1000, verbose_name="Формулировка вопроса"
                    ),
                ),
                (
                    "multiselect",
                    models.BooleanField(verbose_name="Вопрос с мультивыбором"),
                ),
                (
                    "tasks_num",
                    models.IntegerField(verbose_name="Число вариантов ответа"),
                ),
                ("options", django.contrib.postgres.fields.jsonb.JSONField()),
                ("type", models.CharField(max_length=50, verbose_name="Тип вопроса")),
                (
                    "test",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="main.test",
                        verbose_name="Тест",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
                "db_table": "questions",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(default="", max_length=30)),
                ("web_url", models.URLField(default="")),
                ("group", models.IntegerField(default=0)),
                ("admission_year", models.IntegerField(default=0)),
                ("number", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
