# Generated by Django 2.2.10 on 2020-03-05 10:31

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Тема теста')),
                ('description', models.TextField(default='', verbose_name='Описание теста')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Формулировка вопроса')),
                ('options_1', djongo.models.fields.EmbeddedField(default={}, model_container=main.models.Option, null=True, verbose_name='Вариант 1')),
                ('options_2', djongo.models.fields.EmbeddedField(default={}, model_container=main.models.Option, null=True, verbose_name='Вариант 2')),
                ('options_3', djongo.models.fields.EmbeddedField(default={}, model_container=main.models.Option, null=True, verbose_name='Вариант 3')),
                ('options_4', djongo.models.fields.EmbeddedField(default={}, model_container=main.models.Option, null=True, verbose_name='Вариант 4')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Test')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
