# Generated by Django 2.2.10 on 2020-03-03 15:29

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.RemoveField(
            model_name='test',
            name='question',
        ),
        migrations.AddField(
            model_name='test',
            name='tasks',
            field=djongo.models.fields.ListField(default=[], verbose_name=djongo.models.fields.EmbeddedField(model_container='Task', null=True)),
        ),
        migrations.AddField(
            model_name='test',
            name='test_theme',
            field=models.CharField(default='', max_length=200, verbose_name='Тема теста'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=200, verbose_name='Формулировка вопроса')),
                ('options', djongo.models.fields.ListField(default=[], verbose_name=djongo.models.fields.EmbeddedField(model_container='Option', null=True))),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Test')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=200, verbose_name='Вариант ответа')),
                ('is_true', models.BooleanField(verbose_name='Верный ли вариант')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Task')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответа',
            },
        ),
    ]
