# Generated by Django 3.0.5 on 2021-06-01 16:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 16, 44, 34, 672979, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='runningtestsanswers',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 16, 44, 34, 675978, tzinfo=utc), verbose_name='Время запуска теста'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 16, 44, 34, 676664, tzinfo=utc), verbose_name='Время запуска тестирования'),
        ),
        migrations.AlterField(
            model_name='userresult',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 16, 44, 34, 677846, tzinfo=utc), verbose_name='Время прохождения тестирования'),
        ),
    ]
