# Generated by Django 2.2.10 on 2020-03-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='task_num',
            field=models.IntegerField(default=0, verbose_name='Количество заданий в тесте'),
        ),
    ]
