# Generated by Django 2.2.10 on 2020-03-03 19:12

from django.db import migrations, models
import djongo.models.fields
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200303_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='Тест',
        ),
        migrations.RemoveField(
            model_name='option',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='options',
        ),
        migrations.RemoveField(
            model_name='test',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='Вариант 1',
            field=djongo.models.fields.EmbeddedField(default={}, model_container=main.models.Option, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='Вариант 2',
            field=djongo.models.fields.EmbeddedField(default={}, model_container=main.models.Option, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='Вариант 3',
            field=djongo.models.fields.EmbeddedField(default={}, model_container=main.models.Option, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='Вариант 4',
            field=djongo.models.fields.EmbeddedField(default={}, model_container=main.models.Option, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='is_true',
            field=models.BooleanField(verbose_name='Верный'),
        ),
        migrations.AlterField(
            model_name='task',
            name='question',
            field=models.CharField(max_length=200, verbose_name='Формулировка вопроса'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_theme',
            field=models.CharField(max_length=200, verbose_name='Тема теста'),
        ),
    ]
