# Generated by Django 2.2.10 on 2020-03-03 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200303_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Тест',
            new_name='task',
        ),
    ]
