# Generated by Django 2.2.10 on 2020-03-05 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200305_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='test',
        ),
    ]
