# Generated by Django 3.0.5 on 2021-06-09 20:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210601_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='runningtestsanswers',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время запуска теста'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время запуска тестирования'),
        ),
        migrations.AlterField(
            model_name='userresult',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время прохождения тестирования'),
        ),
    ]
