# Generated by Django 2.2.10 on 2020-03-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200303_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.TextField(default='', verbose_name='Описание теста'),
        ),
    ]
