#!/bin/bash

service mongodb start
. /app/venv/bin/activate
python3 /app/quizer/manage.py makemigrations
python3 /app/quizer/manage.py migrate
echo 'from django.contrib.auth.models import Group; l = Group(id=1, name="lecturer"); l.save()' | python3 /app/quizer/manage.py shell
echo 'from django.contrib.auth.models import Group; s = Group(id=2, name="student"); s.save()' | python3 /app/quizer/manage.py shell
echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', '', 'admin')" | python3 /app/quizer/manage.py shell
echo 'from django.contrib.auth.models import User; a = User.objects.get(id=1); a.groups.add(1); a.save(); print("Added user %s to group %s" % (a.username, "lecturer"))'  | python3 /app/quizer/manage.py shell
echo 'from django.contrib.auth.models import User; s = User(id=4, username="user"); s.set_password("password"); s.groups.add(2); s.save()' | python3 /app/quizer/manage.py shell
echo 'from main.models import Subject; s = Subject(id=1, lecturer_id=1, name="Python", description="PL Python"); s.save()' | python3 /app/quizer/manage.py shell
echo 'from main.models import Test; t = Test(id=1, author_id=1, name="PZ1", duration=300, subject_id=1, tasks_num=5, description="Test based on lecture 1"); t.save()' | python3 /app/quizer/manage.py shell
echo "from main.models import QuestionsStorage; strg = QuestionsStorage.connect_to_mongodb(host='localhost', port='27017', db_name='data'); strg.add_one(question={'formulation': 'First question with multiselect', 'tasks_num': 3, 'multiselect': True, 'with_images': False, 'options': [{'option': 'First true option', 'is_true': True}, {'option': 'Second false option', 'is_true': False}, {'option': 'Third true option', 'is_true': True}]}, test_id=1); strg.add_one(question={'formulation': 'Second question with single answer', 'tasks_num': 2, 'multiselect': False, 'with_images': False, 'options': [{'option': 'False option', 'is_true': False}, {'option': 'True option', 'is_true': True}]}, test_id=1)" | python3 /app/quizer/manage.py shell
python3 /app/quizer/manage.py runserver 0.0.0.0:8000 --noreload
