#!/bin/bash

cd /usr/share/python3/quizer
. /usr/share/python3/venv/bin/activate

python manage.py makemigrations
python manage.py migrate

echo 'from django.contrib.auth.models import Group; l = Group(id=1, name="lecturer"); l.save()' | python manage.py shell
echo 'from django.contrib.auth.models import Group; s = Group(id=2, name="student"); s.save()' | python manage.py shell
echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', '', 'admin')" | python manage.py shell

if [[ ! -z "${DEMONSTRATION_VARIANT}" ]]; then
  echo 'from django.contrib.auth.models import User; a = User.objects.get(id=1); a.groups.add(1); a.save(); print("Added user %s to group %s" % (a.username, "lecturer"))'  | python manage.py shell
  echo 'from django.contrib.auth.models import User; s = User(id=4, username="user"); s.set_password("password"); s.groups.add(2); s.save()' | python manage.py shell
  echo 'from main.models import Subject; s = Subject(id=1, name="Python", description="PL Python"); s.save()' | python manage.py shell
  echo 'from main.models import Subject; s = Subject(id=2, name="OSS", description="Operating systems security"); s.save()' | python manage.py shell
  echo 'from main.models import Test; t = Test(id=1, author_id=1, name="PZ1", duration=300, subject_id=1, tasks_num=2, description="Test based on lecture 1. Learn language basics"); t.save()' | python manage.py shell
  echo 'from main.models import Test; t = Test(id=3, author_id=1, name="PZ2", duration=60, subject_id=1, tasks_num=6, description="Test based on lecture 2. Learn language infrastructure - work with IDE PyCharm"); t.save()' | python manage.py shell
  echo 'from main.models import Test; t = Test(id=2, author_id=1, name="First pair - getting to know git", duration=300, subject_id=2, tasks_num=5, description="Work with local gitlab"); t.save()' | python manage.py shell
  echo "from pymongo import MongoClient; from django.conf import settings; from main.mongo import QuestionsStorage; strg = QuestionsStorage.connect(db=MongoClient()[settings.DATABASES['default']['NAME']]); strg.add_one(question={'formulation': 'First question with multiselect', 'tasks_num': 3, 'multiselect': True, 'with_images': False, 'options': [{'option': 'First true option', 'is_true': True}, {'option': 'Second false option', 'is_true': False}, {'option': 'Third true option', 'is_true': True}]}, test_id=1); strg.add_one(question={'formulation': 'Second question with single answer', 'tasks_num': 2, 'multiselect': False, 'with_images': False, 'options': [{'option': 'False option', 'is_true': False}, {'option': 'True option', 'is_true': True}]}, test_id=1)" | python manage.py shell
fi

python manage.py runserver 0.0.0.0:$PORT
