#!/bin/bash

cd /usr/share/python3/quizer
. /usr/share/python3/venv/bin/activate

# run migrations
python manage.py makemigrations
python manage.py migrate
echo yes | python manage.py collectstatic

# add default groups and users
echo 'from django.contrib.auth.models import Group; l = Group(id=1, name="lecturer"); l.save()' | python manage.py shell
echo 'from django.contrib.auth.models import Group; s = Group(id=2, name="student"); s.save()' | python manage.py shell
echo 'from django.contrib.auth.models import User; u = User.objects.create_superuser("admin", "", "admin"); u.groups.add(1)' | python manage.py shell

WORKERS_NUM="${WORKERS_NUM:-2}"

gunicorn -w ${WORKERS_NUM} -k uvicorn.workers.UvicornWorker  -b 0.0.0.0:80 quizer.asgi:application
