#!/bin/bash

cd /usr/share/python3/quizer
. /usr/share/python3/venv/bin/activate

if [[ ! -z "${MONGO_HOST}" ]]; then
  file="$(echo "$(cat /usr/share/python3/venv/lib/python3.7/site-packages/pymongo/mongo_client.py)")"
  echo "${file}" | sed "s/HOST = \"localhost\"/HOST = \"${MONGO_HOST}\"/" > /usr/share/python3/venv/lib/python3.7/site-packages/pymongo/mongo_client.py
fi

python manage.py makemigrations
python manage.py migrate
echo yes | python manage.py collectstatic

echo 'from django.contrib.auth.models import Group; l = Group(id=1, name="lecturer"); l.save()' | python manage.py shell
echo 'from django.contrib.auth.models import Group; s = Group(id=2, name="student"); s.save()' | python manage.py shell
echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', '', 'admin')" | python manage.py shell 2> /dev/null
echo 'from django.contrib.auth.models import User; a = User.objects.get(id=1); a.groups.add(1); a.save(); print("Added user %s to group %s" % (a.username, "lecturer"))'  | python manage.py shell

if [[ ! -z "${DEMONSTRATION_VARIANT}" ]]; then
  echo 'from django.contrib.auth.models import User; s = User(id=4, username="user"); s.set_password("password"); s.groups.add(2); s.save()' | python manage.py shell 2> /dev/null
  echo 'from main.models import Subject; s = Subject(id=1, name="Python", description="PL Python"); s.save()' | python manage.py shell > /dev/null
  echo 'from main.models import Subject; s = Subject(id=2, name="OSS", description="Operating systems security"); s.save()' | python manage.py shell > /dev/null
  echo 'from main.models import Test; t = Test(id=1, author_id=1, name="PZ1", duration=300, subject_id=1, tasks_num=2, description="Test based on lecture 1. Learn language basics"); t.save()' | python manage.py shell 2> /dev/null
  echo 'from main.models import Test; t = Test(id=3, author_id=1, name="PZ2", duration=60, subject_id=1, tasks_num=6, description="Test based on lecture 2. Learn language infrastructure - work with IDE PyCharm"); t.save()' | python manage.py shell 2> /dev/null
  echo 'from main.models import Test; t = Test(id=2, author_id=1, name="First pair - getting to know git", duration=300, subject_id=2, tasks_num=5, description="Work with local gitlab"); t.save()' | python manage.py shell 2> /dev/null
fi

SETTINGS="$(echo "$(cat ./quizer/settings.py)")"

if [[ ! -z "${AUTH_URL}" ]]; then
  AUTH_URL="${AUTH_URL}"
else
  AUTH_URL=http://sms.gitwork.ru/auth/public_key/
fi

SETTINGS="${SETTINGS/<AUTH_URL>/${AUTH_URL}}"

if [[ ! -z "${URL_PREFIX}" ]]; then
  URLS="$(echo "$(cat ./quizer/urls.py)")"
  URLS="${URLS/\'api\/\'/\'${URL_PREFIX}\/api/\'}"
  URLS="${URLS//\'\'/\'${URL_PREFIX}\/\'}"
  echo "${URLS}" > ./quizer/urls.py

  ROUTING="$(echo "$(cat ./quizer/routing.py)")"
  ROUTING="${ROUTING/available_tests/${URL_PREFIX}\/available_tests}"
  echo "${ROUTING}" > ./quizer/routing.py

  SETTINGS="${SETTINGS//\'\/static\/\'/\'\/static\/${URL_PREFIX}\/\'}"
  SETTINGS="${SETTINGS//\'\/media\/\'/\'\/media\/${URL_PREFIX}\/\'}"
fi

echo "${SETTINGS}" > ./quizer/settings.py

gunicorn -w 8 -k uvicorn.workers.UvicornWorker  -b 0.0.0.0:80 quizer.asgi:application
