name: Docker

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6.8, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run Postgres
        run: |
          docker run --env-file=.env -d postgres
      - name: Configure app
        run: |
          entrypoint="$(echo "$(cat deploy/entrypoint)")"
          echo "${entrypoint/gunicorn -w $\{WORKERS_NUM\} -k uvicorn.workers.UvicornWorker  -b 0.0.0.0:80 quizer.asgi:application/cd \/usr\/share\/python3\/quizer && \/usr\/share\/python3\/venv\/bin\/python runtests.py}" > deploy/entrypoint
      - name: Build docker container & running tests
        run: |
          MONGO_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mongodb)
          docker build -t quizer .
          docker run --env-file=.env quizer
